services:

  proxy:
    build:
      context: ..
      dockerfile: Dockerfile
    image: arulrajnet/basic-auth-proxy:dev
    ports:
      - "80:80"
    command:
      - basic-auth-proxy
      - --address=0.0.0.0
      - --port=80
      - --timeout=30
      - --proxy-path=/auth/
      - --upstream=http://nagios_legacy:80/

  nagios_legacy:
    image: jasonrivers/nagios:latest
    ports:
      - 80
    environment:
      NAGIOSADMIN_USER: nagiosadmin
      NAGIOSADMIN_PASS: nagiosadmin
