services:

  # Basic Auth Proxy Service build for host machine architecture for development
  proxy:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: ${GIT_COMMIT:-$(git describe --tags --always --dirty)}
        VERSION: ${VERSION:-dev}
    image: arulrajnet/basic-auth-proxy:dev
    ports:
      - "80:80"
    command:
      - basic-auth-proxy
      - --address=0.0.0.0
      - --port=80
      - --proxy-prefix=/auth/
      - --upstream=http://192.168.1.232:32836/
      - --log-level=debug

  nagios_legacy:
    image: jasonrivers/nagios:latest
    ports:
      - 80
    environment:
      NAGIOSADMIN_USER: nagiosadmin
      NAGIOSADMIN_PASS: nagiosadmin
