services:

  # Basic Auth Proxy Service build for host machine architecture for development
  proxy:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: ${GIT_COMMIT}
        VERSION: ${VERSION}
        TARGETPLATFORM: ${TARGETPLATFORM}
    image: arulrajnet/basic-auth-proxy:dev
    ports:
      - "8080:8080"
    command:
      - basic-auth-proxy
      - --address=0.0.0.0
      - --port=8080
      - --proxy-prefix=/_auth/
      - --upstream=http://nagios_legacy:80/
      - --log-level=debug
    # environment:
    #   BAP_PROXY_ADDRESS: "0.0.0.0"
    #   BAP_PROXY_PORT: "8080"
    #   BAP_PROXY_PREFIX: "/_auth/"
    #   BAP_UPSTREAM_URL: "http://nagios_legacy:80/"
    #   BAP_LOG_LEVEL: "debug"
    # volumes:
    #   - ./../config.yaml:/app/config.yaml

  nagios_legacy:
    image: jasonrivers/nagios:latest
    ports:
      - 80
    environment:
      NAGIOSADMIN_USER: nagiosadmin
      NAGIOSADMIN_PASS: nagiosadmin
