version: "2"
run:
  deadline: 120s
  # Default concurrency is a available CPU number
  concurrency: 4
  # Timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
  # Exit code when at least one issue was found, default is 1
  issues-exit-code: 1
  # Include test files or not, default is true
  tests: true
  # Default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true
  # Allow multiple parallel golangci-lint instances running.
  # If false (default) - golangci-lint acquires file lock on start.
  allow-parallel-runners: false

# Output configuration options
output:
  # Format: colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  format: colored-line-number
  # Print lines of code with issue, default is true
  print-issued-lines: true
  # Print linter name in the end of issue text, default is true
  print-linter-name: true
  # Make issues output unique by line, default is true
  uniq-by-line: true
  # Add a prefix to the output file references, default is no prefix
  path-prefix: ""

linters:
  enable:
    - govet
    - ineffassign
    - goconst
    # - gofmt
    # - goimports
    - gosec
    # - gosimple
    - staticcheck
    # - typecheck
    - unused
    - bodyclose
    - dogsled
    - goprintffuncname
    - misspell
    - prealloc
    - copyloopvar
    # - stylecheck
    - unconvert
    - gocritic
    - revive
  disable-all: true

# Linter settings
linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/arulrajnet/basic-auth-proxy

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - scopelint
        - bodyclose
        - unconvert
        - gocritic
        - gosec
        - goconst
        - revive
    - path: _test\.go
      linters:
        - revive
      text: "dot-imports:"
    # If we have tests in shared test folders, these can be less strictly linted
    - path: tests/.*_tests\.go
      linters:
        - revive
        - bodyclose
        - stylecheck
