version: "2"

run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - goconst
    - gosec
    - staticcheck
    - unused
    - bodyclose
    - dogsled
    - goprintffuncname
    - misspell
    - prealloc
    - copyloopvar
    - unconvert
    - gocritic
    - revive
    - errcheck

linters-settings:
  govet:
    enable:
      - shadow
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
      - name: package-comments
        disabled: true
      - name: unused-parameter
        disabled: true
      - name: var-naming
        disabled: true

issues:
  exclude-use-default: false
  exclude:
    - "G104: Errors unhandled"
  exclude-rules:
    - text: "stutters"
    - path: _test\.go
      linters:
        - revive
        - bodyclose
        - unconvert
        - gocritic
        - gosec
        - goconst
