version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    govet:
      enable:
        - shadow
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
        - name: package-comments
          disabled: true
        - name: unused-parameter
          disabled: true
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    rules:
      - text: stutters
        linters:
          - revive
      - linters:
          - bodyclose
          - goconst
          - gocritic
          - gosec
          - revive
          - unconvert
        path: _test\.go
      - path: (.+)\.go$
        text: 'G104: Errors unhandled'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
